//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeographicalLocationService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SubRegion { get; set; }
        public Nullable<byte> TouristRating { get; set; }
        public Nullable<System.DateTime> EstablishedOn { get; set; }
        public Nullable<int> EstimatedPopulation { get; set; }
        public string CountryCode { get; set; }
    }
}
